const Data = [
  {
    id: 1,
    letter: require("./Words/A.jpg"),
    text: "is for...",
    photo: require("./Pictures/Ant.jpg"),
    word: require("./Words/Ant.jpg"),
  },
  {
    id: 2,
    letter: require("./Words/B.jpg"),
    text: "is for...",
    photo: require("./Pictures/Bat.png"),
    word: require("./Words/Bat.jpg"),
  },
  {
    id: 3,
    letter: require("./Words/C.jpg"),
    text: "is for...",
    photo: require("./Pictures/Cat.jpg"),
    word: require("./Words/Cat.jpg"),
  },
  {
    id: 4,
    letter: require("./Words/D.jpg"),
    text: "is for...",
    photo: require("./Pictures/Oosha.jpg"),
    word: require("./Words/Dog.jpg"),
  },
  {
    id: 5,
    letter: require("./Words/E.jpg"),
    text: "is for...",
    photo: require("./Pictures/Egg.jpg"),
    word: require("./Words/Egg.jpg"),
  },
  {
    id: 6,
    letter: require("./Words/F.jpg"),
    text: "is for...",
    photo: require("./Pictures/Frog.jpg"),
    word: require("./Words/Frog.jpg"),
  },
  {
    id: 7,
    letter: require("./Words/G.jpg"),
    text: "is for...",
    photo: require("./Pictures/Goat.jpg"),
    word: require("./Words/Goat.jpg"),
  },
  {
    id: 8,
    letter: require("./Words/H.jpg"),
    text: "is for...",
    photo: require("./Pictures/Hat.png"),
    word: require("./Words/Hat.jpg"),
  },
  {
    id: 9,
    letter: require("./Words/I.jpg"),
    text: "is for...",
    photo: require("./Pictures/Ink.jpg"),
    word: require("./Words/Ink.jpg"),
  },
  {
    id: 10,
    letter: require("./Words/J.jpg"),
    text: "is for...",
    photo: require("./Pictures/Joey.jpg"),
    word: require("./Words/Joey.jpg"),
  },
  {
    id: 11,
    letter: require("./Words/K.jpg"),
    text: "is for...",
    photo: require("./Pictures/Kite.jpg"),
    word: require("./Words/Kite.jpg"),
  },
  {
    id: 12,
    letter: require("./Words/L.jpg"),
    text: "is for...",
    photo: require("./Pictures/Lion.jpg"),
    word: require("./Words/Lion.jpg"),
  },
  {
    id: 13,
    letter: require("./Words/M.jpg"),
    text: "is for...",
    photo: require("./Pictures/Moon.jpg"),
    word: require("./Words/Moon.jpg"),
  },
  {
    id: 14,
    letter: require("./Words/N.jpg"),
    text: "is for...",
    photo: require("./Pictures/Nut.jpg"),
    word: require("./Words/Nut.jpg"),
  },
  {
    id: 15,
    letter: require("./Words/O.jpg"),
    text: "is for...",
    photo: require("./Pictures/Owl.jpg"),
    word: require("./Words/Owl.jpg"),
  },
  {
    id: 16,
    letter: require("./Words/P.jpg"),
    text: "is for...",
    photo: require("./Pictures/Pony.jpg"),
    word: require("./Words/Pony.jpg"),
  },
  {
    id: 17,
    letter: require("./Words/Q.jpg"),
    text: "is for...",
    photo: require("./Pictures/Queen.jpg"),
    word: require("./Words/Queen.jpg"),
  },
  {
    id: 18,
    letter: require("./Words/R.jpg"),
    text: "is for...",
    photo: require("./Pictures/Robot.jpg"),
    word: require("./Words/Robot.jpg"),
  },
  {
    id: 19,
    letter: require("./Words/S.jpg"),
    text: "is for...",
    photo: require("./Pictures/Sun.jpg"),
    word: require("./Words/Sun.jpg"),
  },
  {
    id: 20,
    letter: require("./Words/T.jpg"),
    text: "is for...",
    photo: require("./Pictures/Tree.jpg"),
    word: require("./Words/Tree.jpg"),
  },
  {
    id: 21,
    letter: require("./Words/U.jpg"),
    text: "is for...",
    photo: require("./Pictures/Up.jpg"),
    word: require("./Words/Up.jpg"),
  },
  {
    id: 22,
    letter: require("./Words/V.jpg"),
    text: "is for...",
    photo: require("./Pictures/Van.jpg"),
    word: require("./Words/Van.jpg"),
  },
  {
    id: 23,
    letter: require("./Words/W.jpg"),
    text: "is for...",
    photo: require("./Pictures/Web.jpg"),
    word: require("./Words/Web.jpg"),
  },
  {
    id: 24,
    letter: require("./Words/X.jpg"),
    text: "is for...",
    photo: require("./Pictures/Xray.png"),
    word: require("./Words/Xray.jpg"),
  },
  {
    id: 25,
    letter: require("./Words/Y.jpg"),
    text: "is for...",
    photo: require("./Pictures/Yarn.jpg"),
    word: require("./Words/Yarn.jpg"),
  },
  {
    id: 26,
    letter: require("./Words/Z.jpg"),
    text: "is for...",
    photo: require("./Pictures/Zebra.jpg"),
    word: require("./Words/Zebra.jpg"),
  },
];

export default Data;
