const Data = [
  {
    id: 1,
    letter: require("./Words/A.jpg"),
    text: "is for...",
    photo: require("./Movies/Ant.mp4"),
    word: require("./Words/Ant.jpg"),
  },
  {
    id: 2,
    letter: require("./Words/B.jpg"),
    text: "is for...",
    photo: require("./Movies/Bat.mp4"),
    word: require("./Words/Bat.jpg"),
  },
  {
    id: 3,
    letter: require("./Words/C.jpg"),
    text: "is for...",
    photo: require("./Movies/Cat.mp4"),
    word: require("./Words/Cat.jpg"),
  },
  {
    id: 4,
    letter: require("./Words/D.jpg"),
    text: "is for...",
    photo: require("./Movies/Oosha.mp4"),
    word: require("./Words/Dog.jpg"),
  },
  {
    id: 5,
    letter: require("./Words/E.jpg"),
    text: "is for...",
    photo: require("./Movies/Egg.mp4"),
    word: require("./Words/Egg.jpg"),
  },
  {
    id: 6,
    letter: require("./Words/F.jpg"),
    text: "is for...",
    photo: require("./Movies/Frog.mp4"),
    word: require("./Words/Frog.jpg"),
  },
  {
    id: 7,
    letter: require("./Words/G.jpg"),
    text: "is for...",
    photo: require("./Movies/Goat.mp4"),
    word: require("./Words/Goat.jpg"),
  },
  {
    id: 8,
    letter: require("./Words/H.jpg"),
    text: "is for...",
    photo: require("./Movies/Hat.mp4"),
    word: require("./Words/Hat.jpg"),
  },
  {
    id: 9,
    letter: require("./Words/I.jpg"),
    text: "is for...",
    photo: require("./Movies/Ink.mp4"),
    word: require("./Words/Ink.jpg"),
  },
  {
    id: 10,
    letter: require("./Words/J.jpg"),
    text: "is for...",
    photo: require("./Movies/Joey.mp4"),
    word: require("./Words/Joey.jpg"),
  },
  {
    id: 11,
    letter: require("./Words/K.jpg"),
    text: "is for...",
    photo: require("./Movies/Kite.mp4"),
    word: require("./Words/Kite.jpg"),
  },
  {
    id: 12,
    letter: require("./Words/L.jpg"),
    text: "is for...",
    photo: require("./Movies/Lion.mp4"),
    word: require("./Words/Lion.jpg"),
  },
  {
    id: 13,
    letter: require("./Words/M.jpg"),
    text: "is for...",
    photo: require("./Movies/Moon.mp4"),
    word: require("./Words/Moon.jpg"),
  },
  {
    id: 14,
    letter: require("./Words/N.jpg"),
    text: "is for...",
    photo: require("./Movies/Nut.mp4"),
    word: require("./Words/Nut.jpg"),
  },
  {
    id: 15,
    letter: require("./Words/O.jpg"),
    text: "is for...",
    photo: require("./Movies/Owl.mp4"),
    word: require("./Words/Owl.jpg"),
  },
  {
    id: 16,
    letter: require("./Words/P.jpg"),
    text: "is for...",
    photo: require("./Movies/Pony.mp4"),
    word: require("./Words/Pony.jpg"),
  },
  {
    id: 17,
    letter: require("./Words/Q.jpg"),
    text: "is for...",
    photo: require("./Movies/Queen.mp4"),
    word: require("./Words/Queen.jpg"),
  },
  {
    id: 18,
    letter: require("./Words/R.jpg"),
    text: "is for...",
    photo: require("./Movies/Robot.mp4"),
    word: require("./Words/Robot.jpg"),
  },
  {
    id: 19,
    letter: require("./Words/S.jpg"),
    text: "is for...",
    photo: require("./Movies/Sun.mp4"),
    word: require("./Words/Sun.jpg"),
  },
  {
    id: 20,
    letter: require("./Words/T.jpg"),
    text: "is for...",
    photo: require("./Movies/Tree.mp4"),
    word: require("./Words/Tree.jpg"),
  },
  {
    id: 21,
    letter: require("./Words/U.jpg"),
    text: "is for...",
    photo: require("./Movies/Up.mp4"),
    word: require("./Words/Up.jpg"),
  },
  {
    id: 22,
    letter: require("./Words/V.jpg"),
    text: "is for...",
    photo: require("./Movies/Van.mp4"),
    word: require("./Words/Van.jpg"),
  },
  {
    id: 23,
    letter: require("./Words/W.jpg"),
    text: "is for...",
    photo: require("./Movies/Web.mp4"),
    word: require("./Words/Web.jpg"),
  },
  {
    id: 24,
    letter: require("./Words/X.jpg"),
    text: "is for...",
    photo: require("./Movies/Xray.mp4"),
    word: require("./Words/Xray.jpg"),
  },
  {
    id: 25,
    letter: require("./Words/Y.jpg"),
    text: "is for...",
    photo: require("./Movies/Yarn.mp4"),
    word: require("./Words/Yarn.jpg"),
  },
  {
    id: 26,
    letter: require("./Words/Z.jpg"),
    text: "is for...",
    photo: require("./Movies/Zebra.mp4"),
    word: require("./Words/Zebra.jpg"),
  },
];

export default Data;
